spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: cn.citi.controller